import 'dart:convert';

// const List<Map<String, dynamic>> US_STATES = [
//     {
//     "id": 0,
//     "parent_id": null,
//     "label": "root",
//     "description": "root",
//     "key": "0",
//     "children": [{
//         "id": 4,
//         "parent_id": 0,
//         "label": "Category velit",
//         "description": "Qui assumenda aut harum placeat.",
//         "key": "4",
//         "children": [{
//             "id": 2,
//             "parent_id": 4,
//             "label": "Category vel",
//             "description": "Quo temporibus sapiente sit est quaerat numquam.",
//             "key": "2",
//             "children": [{
//                 "id": 6,
//                 "parent_id": 2,
//                 "label": "Category fuga",
//                 "description": "Velit dolorum libero in eius ut quisquam.",
//                 "key": "6",
//                 "children": [{
//                     "id": 10,
//                     "parent_id": 6,
//                     "label": "Category adipisci",
//                     "description": "Vero dicta est et voluptatem ut est.",
//                     "key": "10",
//                     "children": [
//                       {
//                         "id": 1,
//                         "user_id": 7,
//                         "auth_user_id": 1,
//                         "temp_id": "a4fa83de-dd0d-3aa1-a09e-cd9c97f34672",
//                         "perm_id": "3d709eeb-02db-39ed-94e0-9d0a15cbe040",
//                         "label": "label offugiat",
//                         "content": "Content of Amet quis distinctio sit odit.",
//                         "private": 0,
//                         "published": 1,
//                         "images": "images/others/hs002.jpeg,images/others/hs003.jpeg,images/others/hs001.jpeg",
//                         "category_id": 10,
//                         "final_category_id": 5,
//                         "final_category_id_from": 1,
//                         "coordinate_longitude": 121.26861838262,
//                         "coordinate_latitude": 31.112503203412,
//                         "coordinate_altitude": 500.001,
//                         "address": "合肥秀英区",
//                         "created_at": "2020-10-31T03:22:25.000000Z",
//                         "updated_at": "2020-10-31T03:22:25.000000Z",
//                         "label": "label offugiat",
//                         "key": "1"
//                       }, {
//                         "id": 11,
//                         "user_id": 6,
//                         "auth_user_id": 1,
//                         "temp_id": "b0d191e0-b5fd-3b89-9766-63b243e5cc20",
//                         "perm_id": "34f8b5fd-917c-374f-aa5c-dae18e8fea65",
//                         "label": "label ofqui",
//                         "content": "Content of Eligendi suscipit quia numquam omnis qui.",
//                         "private": 0,
//                         "published": 1,
//                         "images": "images/others/hs003.jpeg,images/others/hs002.jpeg,images/others/hs001.jpeg",
//                         "category_id": 10,
//                         "final_category_id": 5,
//                         "final_category_id_from": 9,
//                         "coordinate_longitude": 121.27611838262,
//                         "coordinate_latitude": 31.115003203412,
//                         "coordinate_altitude": 500.001,
//                         "address": "合肥东丽区",
//                         "created_at": "2020-10-31T03:22:25.000000Z",
//                         "updated_at": "2020-10-31T03:22:25.000000Z",
//                         "label": "label ofqui",
//                         "key": "11"
//                       }, {
//                         "id": 12,
//                         "user_id": 6,
//                         "auth_user_id": 1,
//                         "temp_id": "46d2c648-4bfa-394d-aa21-460aca19936b",
//                         "perm_id": "ea0baec1-d946-30d6-ba63-9a50705738a2",
//                         "label": "label ofmodi",
//                         "content": "Content of Perspiciatis aut et quasi sit laborum quibusdam.",
//                         "private": 0,
//                         "published": 1,
//                         "images": "images/others/hs002.jpeg,images/others/hs003.jpeg,images/others/hs001.jpeg",
//                         "category_id": 10,
//                         "final_category_id": 6,
//                         "final_category_id_from": 3,
//                         "coordinate_longitude": 121.27511838262,
//                         "coordinate_latitude": 31.119703203412,
//                         "coordinate_altitude": 500.001,
//                         "address": "济南城北区",
//                         "created_at": "2020-10-31T03:22:25.000000Z",
//                         "updated_at": "2020-10-31T03:22:25.000000Z",
//                         "label": "label ofmodi",
//                         "key": "12"
//                       }, {
//                         "id": 14,
//                         "user_id": 2,
//                         "auth_user_id": 1,
//                         "temp_id": "d74c003d-1a06-372f-99a1-cc5232f12662",
//                         "perm_id": "c15de89b-557f-364e-9b1f-f3e6a43a0ef7",
//                         "label": "label ofnobis",
//                         "content": "Content of Quaerat itaque qui aut dolorem quia.",
//                         "private": 0,
//                         "published": 1,
//                         "images": "images/others/hs001.jpeg,images/others/hs002.jpeg,images/others/hs003.jpeg",
//                         "category_id": 10,
//                         "final_category_id": 7,
//                         "final_category_id_from": 5,
//                         "coordinate_longitude": 121.27451838262,
//                         "coordinate_latitude": 31.117803203412,
//                         "coordinate_altitude": 500.001,
//                         "address": "上海山亭区",
//                         "created_at": "2020-10-31T03:22:25.000000Z",
//                         "updated_at": "2020-10-31T03:22:25.000000Z",
//                         "label": "label ofnobis",
//                         "key": "14"
//                       }, {
//                         "id": 23,
//                         "user_id": 1,
//                         "auth_user_id": null,
//                         "temp_id": "5fa1a527a863e",
//                         "perm_id": null,
//                         "label": "label00",
//                         "content": "test contents from postman",
//                         "private": 0,
//                         "published": 0,
//                         "images": "http://images.tornadory.com/image_picker_F0C8F174-4034-48A7-88F9-86A4DF24E609-70729-000289DD57F3B19F.jpg,http://images.tornadory.com/image_picker_410196B2-5BA6-4DEE-AC4A-394D9DDB6097-70729-000289DE776281D8.jpg",
//                         "category_id": 10,
//                         "final_category_id": null,
//                         "final_category_id_from": null,
//                         "coordinate_longitude": 20.001,
//                         "coordinate_latitude": 10.001,
//                         "coordinate_altitude": 30.001,
//                         "address": "fae",
//                         "created_at": "2020-11-03T18:44:55.000000Z",
//                         "updated_at": "2020-11-03T18:44:55.000000Z",
//                         "label": "label00",
//                         "key": "23"
//                       }, {
//                         "id": 25,
//                         "user_id": 1,
//                         "auth_user_id": null,
//                         "temp_id": "5fa1a9d9e59b0",
//                         "perm_id": null,
//                         "label": "标题 测试",
//                         "content": "描述内容 测试 1",
//                         "private": 0,
//                         "published": 0,
//                         "images": "http://images.tornadory.com/image_picker_F0C8F174-4034-48A7-88F9-86A4DF24E609-70729-000289DD57F3B19F.jpg,http://images.tornadory.com/image_picker_410196B2-5BA6-4DEE-AC4A-394D9DDB6097-70729-000289DE776281D8.jpg",
//                         "category_id": 10,
//                         "final_category_id": null,
//                         "final_category_id_from": null,
//                         "coordinate_longitude": 120.1001,
//                         "coordinate_latitude": 39.101,
//                         "coordinate_altitude": 130.001,
//                         "address": "上海市松江区",
//                         "created_at": "2020-11-03T19:04:57.000000Z",
//                         "updated_at": "2020-11-03T19:04:57.000000Z",
//                         "label": "标题 测试",
//                         "key": "25"
//                       }
//                     ]
//                   },
//                   {
//                     "id": 9,
//                     "user_id": 5,
//                     "auth_user_id": 1,
//                     "temp_id": "93974c4a-aab6-3618-b012-36268db3833a",
//                     "perm_id": "8eccee1b-501a-3447-a7d5-de580ccf50fb",
//                     "label": "label ofodit",
//                     "content": "Content of Maiores molestiae occaecati provident et.",
//                     "private": 0,
//                     "published": 1,
//                     "images": "images/others/hs001.jpeg,images/others/hs003.jpeg,images/others/hs002.jpeg",
//                     "category_id": 6,
//                     "final_category_id": 1,
//                     "final_category_id_from": 8,
//                     "coordinate_longitude": 121.27241838262,
//                     "coordinate_latitude": 31.115203203412,
//                     "coordinate_altitude": 500.001,
//                     "address": "香港六枝特区",
//                     "created_at": "2020-10-31T03:22:25.000000Z",
//                     "updated_at": "2020-10-31T03:22:25.000000Z",
//                     "label": "label ofodit",
//                     "key": "9"
//                   }, {
//                     "id": 19,
//                     "user_id": 10,
//                     "auth_user_id": 1,
//                     "temp_id": "078d202a-2da2-36cf-8360-d15f729e1e40",
//                     "perm_id": "7e118047-3059-3d28-a2e7-1efe5ac6cf6c",
//                     "label": "label ofdolor",
//                     "content": "Content of Ex sint non eligendi dolores voluptatem sed.",
//                     "private": 0,
//                     "published": 1,
//                     "images": "images/others/hs001.jpeg,images/others/hs003.jpeg,images/others/hs002.jpeg",
//                     "category_id": 6,
//                     "final_category_id": 6,
//                     "final_category_id_from": 3,
//                     "coordinate_longitude": 121.26791838262,
//                     "coordinate_latitude": 31.117603203412,
//                     "coordinate_altitude": 500.001,
//                     "address": "北京清河区",
//                     "created_at": "2020-10-31T03:22:25.000000Z",
//                     "updated_at": "2020-10-31T03:22:25.000000Z",
//                     "label": "label ofdolor",
//                     "key": "19"
//                   }
//                 ]
//               },
//               [{
//                 "id": 5,
//                 "user_id": 1,
//                 "auth_user_id": 1,
//                 "temp_id": "f896739d-3a44-3117-8450-ba535047b740",
//                 "perm_id": "38383ea9-4d7d-3ac7-9651-4737f2a9e99d",
//                 "label": "label ofea",
//                 "content": "Content of Perferendis perspiciatis assumenda expedita.",
//                 "private": 0,
//                 "published": 1,
//                 "images": "images/others/hs001.jpeg,images/others/hs003.jpeg,images/others/hs002.jpeg",
//                 "category_id": 2,
//                 "final_category_id": 3,
//                 "final_category_id_from": 3,
//                 "coordinate_longitude": 121.27281838262,
//                 "coordinate_latitude": 31.113103203412,
//                 "coordinate_altitude": 500.001,
//                 "address": "乌鲁木齐魏都区",
//                 "created_at": "2020-10-31T03:22:25.000000Z",
//                 "updated_at": "2020-10-31T03:22:25.000000Z",
//                 "label": "label ofea",
//                 "key": "5"
//               }, {
//                 "id": 8,
//                 "user_id": 2,
//                 "auth_user_id": 1,
//                 "temp_id": "75655790-218f-3e2b-8a4e-0f55bb973365",
//                 "perm_id": "bca86686-e375-39ec-9c99-2e2ebe4ecf01",
//                 "label": "label ofhic",
//                 "content": "Content of Ut modi omnis nemo voluptate.",
//                 "private": 0,
//                 "published": 1,
//                 "images": "images/others/hs002.jpeg,images/others/hs003.jpeg,images/others/hs001.jpeg",
//                 "category_id": 2,
//                 "final_category_id": 2,
//                 "final_category_id_from": 10,
//                 "coordinate_longitude": 121.27271838262,
//                 "coordinate_latitude": 31.118503203412,
//                 "coordinate_altitude": 500.001,
//                 "address": "澳门沈北新区",
//                 "created_at": "2020-10-31T03:22:25.000000Z",
//                 "updated_at": "2020-10-31T03:22:25.000000Z",
//                 "label": "label ofhic",
//                 "key": "8"
//               }, {
//                 "id": 21,
//                 "user_id": 10,
//                 "auth_user_id": null,
//                 "temp_id": "10001",
//                 "perm_id": null,
//                 "label": "label00",
//                 "content": "test contents from postman",
//                 "private": 0,
//                 "published": 0,
//                 "images": "http://images.tornadory.com/image_picker_F0C8F174-4034-48A7-88F9-86A4DF24E609-70729-000289DD57F3B19F.jpg,http://images.tornadory.com/image_picker_410196B2-5BA6-4DEE-AC4A-394D9DDB6097-70729-000289DE776281D8.jpg",
//                 "category_id": 2,
//                 "final_category_id": null,
//                 "final_category_id_from": null,
//                 "coordinate_longitude": 20.001,
//                 "coordinate_latitude": 10.001,
//                 "coordinate_altitude": 30.001,
//                 "address": "fae",
//                 "created_at": "2020-11-03T18:41:04.000000Z",
//                 "updated_at": "2020-11-03T18:41:04.000000Z",
//                 "label": "label00",
//                 "key": "21"
//               }, {
//                 "id": 22,
//                 "user_id": 10,
//                 "auth_user_id": null,
//                 "temp_id": "5fa1a4c408a3d",
//                 "perm_id": null,
//                 "label": "label00",
//                 "content": "test contents from postman",
//                 "private": 0,
//                 "published": 0,
//                 "images": "http://images.tornadory.com/image_picker_F0C8F174-4034-48A7-88F9-86A4DF24E609-70729-000289DD57F3B19F.jpg,http://images.tornadory.com/image_picker_410196B2-5BA6-4DEE-AC4A-394D9DDB6097-70729-000289DE776281D8.jpg",
//                 "category_id": 2,
//                 "final_category_id": null,
//                 "final_category_id_from": null,
//                 "coordinate_longitude": 20.001,
//                 "coordinate_latitude": 10.001,
//                 "coordinate_altitude": 30.001,
//                 "address": "fae",
//                 "created_at": "2020-11-03T18:43:16.000000Z",
//                 "updated_at": "2020-11-03T18:43:16.000000Z",
//                 "label": "label00",
//                 "key": "22"
//               }]
//             ]
//           }, {
//             "id": 3,
//             "parent_id": 4,
//             "label": "Category impedit",
//             "description": "Numquam vel qui et ut.",
//             "key": "3",
//             "children": [
//               [{
//                 "id": 4,
//                 "user_id": 3,
//                 "auth_user_id": 1,
//                 "temp_id": "d9c33416-6cb6-3a3c-b670-8d99eb7b423a",
//                 "perm_id": "033b24e0-9c90-3b0c-90da-b3a3c50fc968",
//                 "label": "label ofut",
//                 "content": "Content of Dolores aut magni aut qui.",
//                 "private": 0,
//                 "published": 1,
//                 "images": "images/others/hs003.jpeg,images/others/hs001.jpeg,images/others/hs002.jpeg",
//                 "category_id": 3,
//                 "final_category_id": 9,
//                 "final_category_id_from": 3,
//                 "coordinate_longitude": 121.27301838262,
//                 "coordinate_latitude": 31.118603203412,
//                 "coordinate_altitude": 500.001,
//                 "address": "哈尔滨翔安区",
//                 "created_at": "2020-10-31T03:22:25.000000Z",
//                 "updated_at": "2020-10-31T03:22:25.000000Z",
//                 "label": "label ofut",
//                 "key": "4"
//               }, {
//                 "id": 18,
//                 "user_id": 10,
//                 "auth_user_id": 1,
//                 "temp_id": "46b52341-385c-3cbd-902d-9fb40bc6628c",
//                 "perm_id": "b55a7db5-2330-350d-bab8-daf9762cce53",
//                 "label": "label ofquis",
//                 "content": "Content of Est aut animi fuga. Recusandae qui facilis sit.",
//                 "private": 0,
//                 "published": 1,
//                 "images": "images/others/hs001.jpeg,images/others/hs003.jpeg,images/others/hs002.jpeg",
//                 "category_id": 3,
//                 "final_category_id": 1,
//                 "final_category_id_from": 6,
//                 "coordinate_longitude": 121.26801838262,
//                 "coordinate_latitude": 31.117603203412,
//                 "coordinate_altitude": 500.001,
//                 "address": "北京滨城区",
//                 "created_at": "2020-10-31T03:22:25.000000Z",
//                 "updated_at": "2020-10-31T03:22:25.000000Z",
//                 "label": "label ofquis",
//                 "key": "18"
//               }, {
//                 "id": 24,
//                 "user_id": 1,
//                 "auth_user_id": null,
//                 "temp_id": "5fa1a5d4bf7f6",
//                 "perm_id": null,
//                 "label": "test 01",
//                 "content": "test 001",
//                 "private": 0,
//                 "published": 0,
//                 "images": "http://images.tornadory.com/image_picker_F0C8F174-4034-48A7-88F9-86A4DF24E609-70729-000289DD57F3B19F.jpg,http://images.tornadory.com/image_picker_410196B2-5BA6-4DEE-AC4A-394D9DDB6097-70729-000289DE776281D8.jpg",
//                 "category_id": 3,
//                 "final_category_id": null,
//                 "final_category_id_from": null,
//                 "coordinate_longitude": 20.001,
//                 "coordinate_latitude": 10.001,
//                 "coordinate_altitude": 40.09,
//                 "address": "addresss 1 2 3 4",
//                 "created_at": "2020-11-03T18:47:48.000000Z",
//                 "updated_at": "2020-11-03T18:47:48.000000Z",
//                 "label": "test 01",
//                 "key": "24"
//               }]
//             ]
//           },
//           [{
//             "id": 7,
//             "user_id": 2,
//             "auth_user_id": 1,
//             "temp_id": "70c32863-d621-3828-957c-ecaaf0dd8309",
//             "perm_id": "7cba0be4-76ee-34ed-bf15-85015c26ac55",
//             "label": "label ofreprehenderit",
//             "content": "Content of Esse rem odit tenetur ut modi delectus.",
//             "private": 0,
//             "published": 1,
//             "images": "images/others/hs003.jpeg,images/others/hs002.jpeg,images/others/hs001.jpeg",
//             "category_id": 4,
//             "final_category_id": 4,
//             "final_category_id_from": 4,
//             "coordinate_longitude": 121.27101838262,
//             "coordinate_latitude": 31.118403203412,
//             "coordinate_altitude": 500.001,
//             "address": "沈阳淄川区",
//             "created_at": "2020-10-31T03:22:25.000000Z",
//             "updated_at": "2020-10-31T03:22:25.000000Z",
//             "label": "label ofreprehenderit",
//             "key": "7"
//           }, {
//             "id": 20,
//             "user_id": 4,
//             "auth_user_id": 1,
//             "temp_id": "dec219a1-eb04-3fdb-b5e3-fb14ef0947d1",
//             "perm_id": "705e56b4-1e9b-303d-9e08-3481c2b4e994",
//             "label": "label ofquasi",
//             "content": "Content of Ea tempora sit impedit aliquam possimus.",
//             "private": 0,
//             "published": 1,
//             "images": "images/others/hs001.jpeg,images/others/hs002.jpeg,images/others/hs003.jpeg",
//             "category_id": 4,
//             "final_category_id": 7,
//             "final_category_id_from": 3,
//             "coordinate_longitude": 121.27421838262,
//             "coordinate_latitude": 31.112403203412,
//             "coordinate_altitude": 500.001,
//             "address": "石家庄高港区",
//             "created_at": "2020-10-31T03:22:25.000000Z",
//             "updated_at": "2020-10-31T03:22:25.000000Z",
//             "label": "label ofquasi",
//             "key": "20"
//           }]
//         ]
//       }, {
//         "id": 5,
//         "parent_id": 0,
//         "label": "Category animi",
//         "description": "Eum necessitatibus aut dolorem sunt dolorum.",
//         "key": "5",
//         "children": [{
//             "id": 7,
//             "parent_id": 5,
//             "label": "Category officiis",
//             "description": "Aspernatur a a id ut dolorem.",
//             "key": "7",
//             "children": [
//               []
//             ]
//           }, {
//             "id": 8,
//             "parent_id": 5,
//             "label": "Category quia",
//             "description": "Sapiente dolor sunt velit quo.",
//             "key": "8",
//             "children": [{
//                 "id": 9,
//                 "parent_id": 8,
//                 "label": "Category voluptatem",
//                 "description": "Quaerat harum debitis fugit sequi.",
//                 "key": "9",
//                 "children": [{
//                     "id": 1,
//                     "parent_id": 9,
//                     "label": "Category excepturi",
//                     "description": "A pariatur molestias sit suscipit temporibus.",
//                     "key": "1",
//                     "children": [
//                       [{
//                         "id": 6,
//                         "user_id": 2,
//                         "auth_user_id": 1,
//                         "temp_id": "e8e7e75e-8745-366b-9e30-813c0a1a5b89",
//                         "perm_id": "efc3af25-e5e3-319e-b8ad-d6800754985e",
//                         "label": "label ofquas",
//                         "content": "Content of Velit possimus dolor ullam sit iusto nobis.",
//                         "private": 0,
//                         "published": 1,
//                         "images": "images/others/hs001.jpeg,images/others/hs002.jpeg,images/others/hs003.jpeg",
//                         "category_id": 1,
//                         "final_category_id": 4,
//                         "final_category_id_from": 9,
//                         "coordinate_longitude": 121.27141838262,
//                         "coordinate_latitude": 31.113603203412,
//                         "coordinate_altitude": 500.001,
//                         "address": "武汉吉利区",
//                         "created_at": "2020-10-31T03:22:25.000000Z",
//                         "updated_at": "2020-10-31T03:22:25.000000Z",
//                         "label": "label ofquas",
//                         "key": "6"
//                       }, {
//                         "id": 17,
//                         "user_id": 8,
//                         "auth_user_id": 1,
//                         "temp_id": "406f3e01-885f-3fcc-9e21-a18db2527b74",
//                         "perm_id": "f173d29f-8a76-3b80-9724-ef43c99f24fd",
//                         "label": "label ofinventore",
//                         "content": "Content of Qui praesentium qui consequuntur sit.",
//                         "private": 0,
//                         "published": 1,
//                         "images": "images/others/hs003.jpeg,images/others/hs002.jpeg,images/others/hs001.jpeg",
//                         "category_id": 1,
//                         "final_category_id": 5,
//                         "final_category_id_from": 7,
//                         "coordinate_longitude": 121.26981838262,
//                         "coordinate_latitude": 31.112003203412,
//                         "coordinate_altitude": 500.001,
//                         "address": "长沙安次区",
//                         "created_at": "2020-10-31T03:22:25.000000Z",
//                         "updated_at": "2020-10-31T03:22:25.000000Z",
//                         "label": "label ofinventore",
//                         "key": "17"
//                       }]
//                     ]
//                   },
//                   [{
//                     "id": 13,
//                     "user_id": 6,
//                     "auth_user_id": 1,
//                     "temp_id": "15593ef0-faba-3e4d-a570-48c7dce1bba5",
//                     "perm_id": "2e16ed4e-61d9-32ce-bbf4-ba7397c230de",
//                     "label": "label ofalias",
//                     "content": "Content of Dolorem et qui voluptatem dolores optio repellat.",
//                     "private": 0,
//                     "published": 1,
//                     "images": "images/others/hs002.jpeg,images/others/hs003.jpeg,images/others/hs001.jpeg",
//                     "category_id": 9,
//                     "final_category_id": 1,
//                     "final_category_id_from": 8,
//                     "coordinate_longitude": 121.27101838262,
//                     "coordinate_latitude": 31.113703203412,
//                     "coordinate_altitude": 500.001,
//                     "address": "天津魏都区",
//                     "created_at": "2020-10-31T03:22:25.000000Z",
//                     "updated_at": "2020-10-31T03:22:25.000000Z",
//                     "label": "label ofalias",
//                     "key": "13"
//                   }, {
//                     "id": 15,
//                     "user_id": 5,
//                     "auth_user_id": 1,
//                     "temp_id": "e2449a49-7153-3a58-8091-20207f355005",
//                     "perm_id": "6bb3e453-bbc0-3dbe-b267-1c51913e0e1f",
//                     "label": "label ofqui",
//                     "content": "Content of Rerum eveniet porro fuga.",
//                     "private": 0,
//                     "published": 1,
//                     "images": "images/others/hs003.jpeg,images/others/hs002.jpeg,images/others/hs001.jpeg",
//                     "category_id": 9,
//                     "final_category_id": 9,
//                     "final_category_id_from": 4,
//                     "coordinate_longitude": 121.27101838262,
//                     "coordinate_latitude": 31.118803203412,
//                     "coordinate_altitude": 500.001,
//                     "address": "太原萧山区",
//                     "created_at": "2020-10-31T03:22:25.000000Z",
//                     "updated_at": "2020-10-31T03:22:25.000000Z",
//                     "label": "label ofqui",
//                     "key": "15"
//                   }]
//                 ]
//               },
//               [{
//                 "id": 3,
//                 "user_id": 3,
//                 "auth_user_id": 1,
//                 "temp_id": "ea421fec-a710-32e5-8d25-8d1e2d84a055",
//                 "perm_id": "a92b27eb-1305-3154-8a24-f33c771c92a5",
//                 "label": "label ofquo",
//                 "content": "Content of Tenetur blanditiis maxime enim error numquam et.",
//                 "private": 0,
//                 "published": 1,
//                 "images": "images/others/hs002.jpeg,images/others/hs001.jpeg,images/others/hs003.jpeg",
//                 "category_id": 8,
//                 "final_category_id": 8,
//                 "final_category_id_from": 5,
//                 "coordinate_longitude": 121.27421838262,
//                 "coordinate_latitude": 31.119503203412,
//                 "coordinate_altitude": 500.001,
//                 "address": "武汉高坪区",
//                 "created_at": "2020-10-31T03:22:25.000000Z",
//                 "updated_at": "2020-10-31T03:22:25.000000Z",
//                 "label": "label ofquo",
//                 "key": "3"
//               }, {
//                 "id": 10,
//                 "user_id": 2,
//                 "auth_user_id": 1,
//                 "temp_id": "8d277ad6-2354-3bc3-b3a7-e3fcd6660a15",
//                 "perm_id": "7bda9672-7c6c-35a8-8332-bd068aaf4f13",
//                 "label": "label ofut",
//                 "content": "Content of Est vero officia natus omnis quia ab.",
//                 "private": 0,
//                 "published": 1,
//                 "images": "images/others/hs003.jpeg,images/others/hs001.jpeg,images/others/hs002.jpeg",
//                 "category_id": 8,
//                 "final_category_id": 10,
//                 "final_category_id_from": 5,
//                 "coordinate_longitude": 121.27311838262,
//                 "coordinate_latitude": 31.117603203412,
//                 "coordinate_altitude": 500.001,
//                 "address": "乌鲁木齐萧山区",
//                 "created_at": "2020-10-31T03:22:25.000000Z",
//                 "updated_at": "2020-10-31T03:22:25.000000Z",
//                 "label": "label ofut",
//                 "key": "10"
//               }, {
//                 "id": 16,
//                 "user_id": 1,
//                 "auth_user_id": 1,
//                 "temp_id": "78aa2ab9-1a8a-3f30-864c-be5683d50b9f",
//                 "perm_id": "a48a1067-bf15-3e6d-9f6c-18f359f792be",
//                 "label": "label ofdebitis",
//                 "content": "Content of Quidem nemo aliquid facere dignissimos.",
//                 "private": 0,
//                 "published": 1,
//                 "images": "images/others/hs003.jpeg,images/others/hs001.jpeg,images/others/hs002.jpeg",
//                 "category_id": 8,
//                 "final_category_id": 6,
//                 "final_category_id_from": 7,
//                 "coordinate_longitude": 121.27101838262,
//                 "coordinate_latitude": 31.117203203412,
//                 "coordinate_altitude": 500.001,
//                 "address": "北京兴山区",
//                 "created_at": "2020-10-31T03:22:25.000000Z",
//                 "updated_at": "2020-10-31T03:22:25.000000Z",
//                 "label": "label ofdebitis",
//                 "key": "16"
//               }]
//             ]
//           },
//           [{
//             "id": 2,
//             "user_id": 7,
//             "auth_user_id": 1,
//             "temp_id": "b813c716-f48d-3b21-aa1c-060ca9fbdb57",
//             "perm_id": "d02c6950-006d-3313-b518-f8b339c03ebf",
//             "label": "label ofut",
//             "content": "Content of Ipsa rerum tempore repudiandae rerum quidem.",
//             "private": 0,
//             "published": 1,
//             "images": "images/others/hs002.jpeg,images/others/hs001.jpeg,images/others/hs003.jpeg",
//             "category_id": 5,
//             "final_category_id": 1,
//             "final_category_id_from": 9,
//             "coordinate_longitude": 121.27121838262,
//             "coordinate_latitude": 31.119303203412,
//             "coordinate_altitude": 500.001,
//             "address": "合肥平山区",
//             "created_at": "2020-10-31T03:22:25.000000Z",
//             "updated_at": "2020-10-31T03:22:25.000000Z",
//             "label": "label ofut",
//             "key": "2"
//           }]
//         ]
//       },
//       []
//     ]
//   }
// ];

const List<Map<String, dynamic>> US_STATES = [
  {
    "label": "A",
    "children": [
      {
        "label": "Alabama", 
        "key": "AL",
        "children":[
          {"label": "Alaska", "key": "AK"},
          {"label": "American Samoa", "key": "AS"},
          {"label": "Arizona", "key": "AZ"},
          {"label": "Arkansas", "key": "AR"}
        ]
      },
      {
        "label": "Alaska", 
        "key": "AK",
        "children":[]
      },
      {"label": "American Samoa", "key": "AS"},
      {"label": "Arizona", "key": "AZ"},
      {"label": "Arkansas", "key": "AR"}
    ]
  },
  {
    "label": "C",
    "children": [
      {"label": "California", "key": "CA"},
      {"label": "Colorado", "key": "CO"},
      {"label": "Connecticut", "key": "CT"},
    ]
  },
  {
    "label": "D",
    "children": [
      {"label": "Delaware", "key": "DE"},
      {"label": "District Of Columbia", "key": "DC"},
    ]
  },
  {
    "label": "F",
    "children": [
      {"label": "Federated States Of Micronesia", "key": "FM"},
      {"label": "Florida", "key": "FL"},
    ]
  },
  {
    "label": "G",
    "children": [
      {"label": "Georgia", "key": "GA"},
      {"label": "Guam", "key": "GU"},
    ]
  },
  {
    "label": "H",
    "children": [
      {"label": "Hawaii", "key": "HI"},
    ]
  },
  {
    "label": "I",
    "children": [
      {"label": "Idaho", "key": "ID"},
      {"label": "Illinois", "key": "IL"},
      {"label": "Indiana", "key": "IN"},
      {"label": "Iowa", "key": "IA"},
    ]
  },
  {
    "label": "K",
    "children": [
      {"label": "Kansas", "key": "KS"},
      {"label": "Kentucky", "key": "KY"},
    ]
  },
  {
    "label": "L",
    "children": [
      {"label": "Louisiana", "key": "LA"},
    ]
  },
  {
    "label": "M",
    "children": [
      {"label": "Maine", "key": "ME"},
      {"label": "Marshall Islands", "key": "MH"},
      {"label": "Maryland", "key": "MD"},
      {"label": "Massachusetts", "key": "MA"},
      {"label": "Michigan", "key": "MI"},
      {"label": "Minnesota", "key": "MN"},
      {"label": "Mississippi", "key": "MS"},
      {"label": "Missouri", "key": "MO"},
      {"label": "Montana", "key": "MT"},
    ]
  },
  {
    "label": "N",
    "children": [
      {"label": "Nebraska", "key": "NE"},
      {"label": "Nevada", "key": "NV"},
      {"label": "New Hampshire", "key": "NH"},
      {"label": "New Jersey", "key": "NJ"},
      {"label": "New Mexico", "key": "NM"},
      {"label": "New York", "key": "NY"},
      {"label": "North Carolina", "key": "NC"},
      {"label": "North Dakota", "key": "ND"},
      {"label": "Northern Mariana Islands", "key": "MP"},
    ]
  },
  {
    "label": "O",
    "children": [
      {"label": "Ohio", "key": "OH"},
      {"label": "Oklahoma", "key": "OK"},
      {"label": "Oregon", "key": "OR"},
    ]
  },
  {
    "label": "P",
    "children": [
      {"label": "Palau", "key": "PW"},
      {"label": "Pennsylvania", "key": "PA"},
      {"label": "Puerto Rico", "key": "PR"},
    ]
  },
  {
    "label": "R",
    "children": [
      {"label": "Rhode Island", "key": "RI"},
    ]
  },
  {
    "label": "S",
    "children": [
      {"label": "South Carolina", "key": "SC"},
      {"label": "South Dakota", "key": "SD"},
    ]
  },
  {
    "label": "T",
    "children": [
      {"label": "Tennessee", "key": "TN"},
      {"label": "Texas", "key": "TX"},
    ]
  },
  {
    "label": "U",
    "children": [
      {"label": "Utah", "key": "UT"},
    ]
  },
  {
    "label": "V",
    "children": [
      {"label": "Vermont", "key": "VT"},
      {"label": "Virgin Islands", "key": "VI"},
      {"label": "Virginia", "key": "VA"},
    ]
  },
  {
    "label": "W",
    "children": [
      {"label": "Washington", "key": "WA"},
      {"label": "West Virginia", "key": "WV"},
      {"label": "Wisconsin", "key": "WI"},
      {"label": "Wyoming", "key": "WY"}
    ]
  },
];

String US_STATES_JSON = jsonEncode(US_STATES);