name: fossils_finder
description: Fossils Finder Project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_login: 1.0.14


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  oktoast: ^2.3.1+1
  decorated_flutter: ^0.12.0+1
  demo_widgets: ^0.0.3
  flutter_bmfmap:  ^1.0.2
  # flutter_bmfmap:  ^1.0.2
  # flutter_bmfutils: ^1.0.2

  json_annotation:

  # reorder_tree_list: ^0.1.1
  list_treeview:

  http:
  dio:
  shared_preferences:
  flutter_treeview:

  flutter_swiper: ^1.1.6
  # swipe_stack:

  # flutter_picker:
  image_picker:

  #permission_handler:
  permission_handler:

  fluttertoast:

  # barcode_scan: ^3.0.1
  # qrscan:


dev_dependencies:
  flutter_test:
    sdk: flutter
  amap_map_fluttify:
    # path: /Users/johnnyz/work/sources/flutter/amap_map_fluttify-master/
    path: ./third_party/amap_map_fluttify/

  
  build_runner:
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icons/fossil_icon_512.png
    - images/icons/user.png
    - images/others/hs001.jpeg
    - images/others/hs002.jpeg
    - images/others/hs003.jpeg
    - images/others/hs004.jpeg
    - images/others/hs005.jpeg
    - images/others/hs006.jpeg
    - images/others/hs007.jpeg
    - images/others/hs008.jpeg
    - images/others/hs009.jpeg
    - images/others/hs010.jpg
    - images/others/hs011.jpeg
    - assets/data/posts.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
