name: fossils_finder
description: Fossils Finder Project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  easy_localization: ^2.3.3
  
  flutter_login:
    path: ./third_party/flutter_login-1.0.14/


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  oktoast: ^2.3.1+1
  decorated_flutter: ^0.12.0+1
  demo_widgets: ^0.0.3
  # flutter_bmfmap:  ^1.0.2
  # flutter_bmfmap:  ^1.0.2
  # flutter_bmfutils: ^1.0.2

  json_annotation:

  # reorder_tree_list: ^0.1.1
  list_treeview:

  http:
  dio:
  shared_preferences:
  # flutter_treeview:

  flutter_swiper: ^1.1.6
  # swipe_stack:

  # flutter_picker:
  image_picker:

  #permission_handler:
  permission_handler:

  fluttertoast:

  # barcode_scan: ^3.0.1
  # qrscan: ^0.2.18
  barcode_scan: ^1.0.0
  qr_flutter: ^3.1.0

  #scan QR Code
  # flutter_barcode_scanner: ^1.0.1

  #create QR Code
  # barcode_widget: ^1.5.0

  share: ^0.6.1+1

  #icons
  flutter_icons:

  #db
  sqflite:
  
  cached_network_image:
  
  ali_icons: ^0.0.3
  flex_color_scheme: 2.1.1

  # geolocation:
  # flutter_screenutil: 5.0.0
  photo_view: ^0.4.2

  flushbar: ^1.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  amap_map_fluttify:
    # path: /Users/johnnyz/work/sources/flutter/amap_map_fluttify-master/
    path: ./third_party/amap_map_fluttify/
  flutter_treeview:
    path: ./third_party/flutter_treeview-0.6.0+2/

  
  build_runner:
  json_serializable:
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.8.1

flutter_launcher_name:
  name: "Fossil Hunter"

flutter_icons:
  image_path: "images/icons/fossil_icon_512.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icons/fossil_icon_512.png
    - images/icons/user.png
    - images/icons/shared_gray.png
    - images/icons/marker.png
    - images/icons/marker-blue.png
    - images/icons/marker-red.png
    - images/icons/map-icon-satillite.png
    - images/icons/map-icon-standard.png
    - images/icons/map-amap.png
    - images/icons/map-google.png
    - images/icons/icons8-delete.png
    - images/icons/icons8-checkmark.png
    - images/icons/scanning.png
    - images/icons/qrcode.png
    - images/icons/category.png
    - images/icons/category_gray.png
    - images/icons/comment.png
    - images/icons/comment_gray.png
    - images/icons/lock.png
    - images/icons/lock_gray.png
    - images/icons/map_show.png
    - images/icons/map_show_gray.png
    - images/icons/map_hide_gray.png
    - images/icons/map_hide.png
    - images/icons/password_change.png
    - images/icons/password_change_gray.png
    - images/icons/qrcode_check.png
    - images/icons/qrcode_check_gray.png
    - images/icons/logout.png
    - images/icons/logout_gray.png
    - images/icons/scan.png
    - images/icons/scan_gray.png
    - images/icons/layer.png
    - images/icons/layer_gray.png
    - images/icons/sync_failed.png
    - images/icons/sync_failed_gray.png
    - images/icons/target.png
    - images/icons/target_gray.png
    - images/icons/unlock.png
    - images/icons/unlock_gray.png
    - images/others/hs001.jpeg
    - images/others/hs002.jpeg
    - images/others/hs003.jpeg
    - images/others/hs004.jpeg
    - images/others/hs005.jpeg
    - images/others/hs006.jpeg
    - images/others/hs007.jpeg
    - images/others/hs008.jpeg
    - images/others/hs009.jpeg
    - images/others/hs010.jpg
    - images/others/hs011.jpeg
    - assets/data/posts.json
    - assets/data/qiniu.json
    - assets/data/system_series_stage_table.json
    - assets/translations/en-US.json
    - assets/translations/zh-CN.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
